YourDVVS/YourDVVS/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using DAL.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using BLL.Interfaces;
using Microsoft.Extensions.Logging;
using System.Globalization;
using System.Threading.Tasks;
namespace YourDVVS.Controllers
{
    [Authorize]
    public class SubjectController : Controller
    {        
            private readonly IAccountManagement accountManagement;
            private readonly ISubjectManagement subjectManagement;
            private readonly ILogger<SubjectController> logger;
            public SubjectController(IAccountManagement _accountManagement,
                                     ISubjectManagement _subjectManagement,
                                     ILogger<SubjectController> _logger)
            {
                accountManagement = _accountManagement;
                subjectManagement = _subjectManagement;
                logger = _logger;
            }

            [Authorize]
            public ViewResult SubjectsFirstTerm(string Search)
            {
                var user = accountManagement.GetUser(User.Identity.Name);
                Subject[] subjectsList;
                ViewData["Information"] = "";
                if (user.Role == 3)
                {
                    var student = accountManagement.GetStudent(user.UserId);
                    if (student.Course == 1)
                    {
                        subjectsList = subjectManagement.GetSubjects(3);
                    }
                    else if (student.Course == 2)
                    {
                        subjectsList = subjectManagement.GetSubjects(5);
                    }
                    else
                    {
                        subjectsList = subjectManagement.GetSubjects(1);
                        ViewData["Information"] = "Вибіркові дисципліни для вас не опубліковані.";
                    }

                }
                else
                {
                    subjectsList = new List<Subject>()
                    .Concat(subjectManagement.GetSubjects(3))
                    .Concat(subjectManagement.GetSubjects(5))
                    .ToArray();
                }

                if (!String.IsNullOrEmpty(Search))
                {
                    subjectsList = subjectManagement.GetSubjectsByTitle(Search, subjectsList);
                }
                return View(subjectsList);
            }

            [Authorize]
            public ViewResult SubjectsSecondTerm(string Search)
            {
                var user = accountManagement.GetUser(User.Identity.Name);
                Subject[] subjectsList;
                ViewData["Information"] = "";
                if (user.Role == 3)
                {
                    var student = accountManagement.GetStudent(user.UserId);
                    if (student.Course == 1)
                    {
                        subjectsList = subjectManagement.GetSubjects(4);
                    }
                    else if (student.Course == 2)
                    {
                        subjectsList = subjectManagement.GetSubjects(6);
                    }
                    else
                    {
                        subjectsList = subjectManagement.GetSubjects(1);
                        ViewData["Information"] = "Вибіркові дисципліни для вас не опубліковані.";
                    }

                }
                else
                {
                    subjectsList = new List<Subject>()
                    .Concat(subjectManagement.GetSubjects(4))
                    .Concat(subjectManagement.GetSubjects(6))
                    .ToArray();
                }

                if (!String.IsNullOrEmpty(Search))
                {
                    subjectsList = subjectManagement.GetSubjectsByTitle(Search, subjectsList);
                }
                return View(subjectsList);
            }

            [ResponseCache(NoStore = true, Location = ResponseCacheLocation.None)]
            public IActionResult Index()
            {
                return View();
            }

            

            [Authorize]
            public IActionResult SubjectInfo(int id)
            {
                try
                {
                    var subject = subjectManagement.GetSingleSubjectById(id);
                    ViewData["SubjectName"] = subject.Name;
                    ViewData["NumberOfStudents"] = subject.NumberOfStudents;
                    ViewData["MaxNumberOfStudents"] = subject.MaxNumberOfStudents;
                    ViewData["Description"] = subject.Description;
                    var lecturer = accountManagement.GetLecturer(subject.LecturerId);
                    ViewData["LecturerName"] = lecturer.LastName + " " + lecturer.FirstName[0] + ". " + lecturer.MiddleName[0] + ".";
                    ViewData["FacultyName"] = subject.Faculty;
                    
                }
                catch (System.Exception)
                {
                    return View("Error");
                }
                return View();
            }

            [Authorize(Roles = "3")]
            public void MakeSubjectChoice(int SubjId)
            {
                User user = accountManagement.GetUser(User.Identity.Name);
                subjectManagement.MakeSubjectChoice(user.UserId, SubjId);
                logger.LogInformation("{@User} has made final choice - subject with id {Id} choosen", user, SubjId);
            }

            [Authorize(Roles = "1,2")]
            public async Task<IActionResult> AddNewSubject(Subject subject)
            {
                User user = accountManagement.GetUser(User.Identity.Name);
                if (user.Role == 2) { subject.LecturerId = user.UserId; }
                if (!String.IsNullOrEmpty(subject.Name) && !String.IsNullOrEmpty(subject.Description) && !String.IsNullOrEmpty(subject.Faculty) && subject.Semester != 0)
                {
                    if (user.Role != 2) { subject.LecturerId = accountManagement.GetLecturerId(subject.Lecturer.User.LastName); }
                    subjectManagement.AddNewSubject(subject.Name, subject.Description, subject.Faculty, subject.LecturerId, subject.Semester);
                    return RedirectToAction("Profile", "Account");
                }
                return View();
            }

    }
}

YourDVVS/YourDVVS/Views/Subject/AddNewSubject.cshtml
@using DAL;
@using BLL.Interfaces;
@inject ISubjectManagement subjectManagement;
@inject IAccountManagement accountManagement;
@model DAL.Entities.Subject;
@{
    string[] lecturers = accountManagement.GetLecturers();
}
@{
    ViewData["Title"] = "AddNewSubject";
    if (User.IsInRole("1"))
    {
        Layout = "_LayoutAdmin";
    }
    else if (User.IsInRole("2"))
    {
        Layout = "_LayoutLecturer";
    }
}

    <div id="login-form">
        <h1>Додати предмет</h1>
        @using (Html.BeginForm("AddNewSubject", "Subject", FormMethod.Get))
        {
            @Html.EditorFor(Model => Model.Name, new { htmlAttributes = new { @placeholder = "Назва предмету" } })
            @Html.EditorFor(Model => Model.Faculty, new { htmlAttributes = new { @placeholder = "Факультет" } })
            @Html.TextAreaFor(Model => Model.Description, 4, 38, new { @placeholder = "Опис", @class = "drop-down-list" })

            if (User.IsInRole("1"))
            {
                @Html.DropDownListFor(Model => Model.Lecturer.User.LastName, new SelectList(lecturers),  new { @placeholder = "Викладач", @class = "drop-down-list" })
            }
            @Html.DropDownListFor(Model => Model.Semester,
                  new List<SelectListItem> {
                       new SelectListItem { Value = "3", Text = "Семестр 3" },
                       new SelectListItem { Value = "4", Text = "Семестр 4" },
                       new SelectListItem { Value = "5", Text = "Семестр 5" },
                       new SelectListItem { Value = "6", Text = "Семестр 6" }
                    }, "Семестр",
                  new { @placeholder = "Семестр", @class = "drop-down-list" })
            <button type="submit" name="AddNewSubject" value="Subject">Додати предмет</button>
        }
    </div>

YourDVVS/YourDVVS/Views/Subject/SubjectInfo.cshtml
@{
    ViewData["Title"] = "Subject";
    if (User.IsInRole("1"))
    {
        Layout = "_LayoutAdmin";
    }
    else if (User.IsInRole("2"))
    {
        Layout = "_LayoutLecturer";
    }
    else if (User.IsInRole("3"))
    {
        Layout = "_LayoutStudent";
    }
}


<div class="single-subject">
    <div class="single-subject-header row">
        <div class="col-md-7 single-subject-info">
            <h1>@ViewData["SubjectName"]</h1>
            <p>Кількість студентів, які обрали дисципліну: @ViewData["NumberOfStudents"]/@ViewData["MaxNumberOfStudents"]</p>
        </div>
        <div class="col-md-5 single-subject-lecturer">
            <h1>@ViewData["LecturerName"]</h1>
            <h6>@ViewData["FacultyName"]</h6>
        </div>
    </div>
    <div class="single-subject-info">
        <div class="row">
            <h1>Опис:</h1>
        </div>
        <div class="row">
            <p>@ViewData["Description"]</p>
        </div>
    </div>

</div>

YourDVVS/YourDVVS/Views/Subject/SubjectsFirstTerm.cshtml
@using DAL.Entities;
@using BLL.Interfaces;
@inject ISubjectManagement subjectManagement;
@inject IAccountManagement accountManagement;
@model IEnumerable<DAL.Entities.Subject>
@{
    ViewData["Title"] = "Subjects";
    if (User.IsInRole("1"))
    {
        Layout = "_LayoutAdmin";
    }
    else if (User.IsInRole("2"))
    {
        Layout = "_LayoutLecturer";
    }
    else if (User.IsInRole("3"))
    {
        Layout = "_LayoutStudent";
    }
}

@{
    if (@ViewData["Information"].ToString() == String.Empty)
    {
        <div class="row subject-menu">
            <ul class="redirectToTerms col-md-6">
                <li class="redirectToFirst"><a href="../Subject/SubjectsFirstTerm" style="text-decoration: underline;">Півріччя 1</a></li>
                <li class="redirectToSecond"><a href="../Subject/SubjectsSecondTerm">Півріччя 2</a></li>
            </ul>
            <form asp-controller="Subject" asp-action="SubjectsFirstTerm" method="get" class="SearchBox col-md-6">
                <p>
                    <input type="text" name="Search" class="TextInput">
                    <input class="SearchButton" type="submit" value="Filter" />
                </p>
            </form>
        </div>
    }
    else
    {
        <p class="SubjectsPageViewForOlderStudents">@ViewData["Information"]</p>
    }
}
<div>
    @foreach (var subject in Model)
    {
        User lecturer = accountManagement.GetLecturer(subject.LecturerId);
        <div class="subjects row">

            <div class="col-md-7 all-subjects-info">
                <h1><a asp-controller="Subject" asp-action="SubjectInfo" asp-route-id="@subject.SubjectId">@subject.Name</a></h1>
                <p>Кількість студентів, які обрали дисципліну: @subject.NumberOfStudents</p>
            </div>
            <div class="col-md-4 all-subjects-lecture-info">
                <h1>@lecturer.LastName @lecturer.FirstName[0]. @lecturer.MiddleName[0].</h1>
                <h6>@lecturer.Faculty</h6>
            </div>
        </div>
    }

</div>

YourDVVS/YourDVVS/Views/Subject/SubjectsSecondTerm.cshtml
@using DAL.Entities;
@using BLL.Interfaces;
@inject ISubjectManagement subjectManagement;
@inject IAccountManagement accountManagement;
@model IEnumerable<DAL.Entities.Subject>
@{
    ViewData["Title"] = "Sub";
    if (User.IsInRole("1"))
    {
        Layout = "_LayoutAdmin";
    }
    else if (User.IsInRole("2"))
    {
        Layout = "_LayoutLecturer";
    }
    else if (User.IsInRole("3"))
    {
        Layout = "_LayoutStudent";
    }
}

@{
    if (@ViewData["Information"].ToString() == String.Empty)
    {
        <div class="row subject-menu">
            <ul class="redirectToTerms col-md-6">
                <li class="redirectToFirst"><a href="../Subject/SubjectsFirstTerm">Півріччя 1</a></li>
                <li class="redirectToSecond"><a href="../Subject/SubjectsSecondTerm" style="text-decoration: underline;">Півріччя 2</a></li>
            </ul>
            <form asp-controller="Subject" asp-action="SubjectsSecondTerm" method="get" class="SearchBox col-md-6">
                <p>
                    <input type="text" name="Search" class="TextInput">
                    <input class="SearchButton" type="submit" value="Filter" />
                </p>
            </form>
        </div>
    }
    else
    {
        <p class="SubjectsPageViewForOlderStudents">@ViewData["Information"]</p>
    }
}
<div>
    @foreach (var subject in Model)
    {
        User lecturer = accountManagement.GetLecturer(subject.LecturerId);
        <div class="subjects row">

            <div class="col-md-7 all-subjects-info">
                <h1><a asp-controller="Subject" asp-action="SubjectInfo" asp-route-id="@subject.SubjectId">@subject.Name</a></h1>
                <p>Кількість студентів, які обрали дисципліну: @subject.NumberOfStudents</p>
            </div>
            <div class="col-md-4 all-subjects-lecture-info">
                <h1>@lecturer.LastName @lecturer.FirstName[0]. @lecturer.MiddleName[0].</h1>
                <h6>@lecturer.Faculty</h6>
            </div>
        </div>
    }
</div>